api/urls.py
from django.conf.urls import url
from .users import views as user_views
from .posts import views as post_views

urlpatterns = [
    url(r'^signup', user_views.UserRegistrationView.as_view(), name="signup-api"),
    url(r'^login', user_views.UserLoginView.as_view(), name="login-api"),
    url(r'^users', user_views.UserListView.as_view(), name="users-list-api"),
    url(r'^search', user_views.SearchView.as_view(), name="search-api"),
    url(r'^user/profile', user_views.UserProfileView.as_view(), name="user-profile-api"),
    url(r'^profile/update', user_views.UserProfileUpdateView.as_view(), name="profile-update-api"),
    url(r'^post/create', post_views.PostCreateView.as_view(), name="post-create-api"),
    url(r'^posts/list', post_views.PostsListView.as_view(), name="posts-list-api"),
    url(r'^post/(?P<pk>[^/]+)/update$', post_views.PostUpdateView.as_view(), name="post-update-api"),
    url(r'^post/(?P<post_id>[^/]+)/delete$', post_views.PostDeleteView.as_view(), name="post-delete-api"),
    url(r'^posts$', post_views.PostFeedView.as_view(), name="post-feed-api"),
    url(r'^user/(?P<user_id>[^/]+)/follow$', user_views.FollowView.as_view(), name="user-follow-api"),
    url(r'^user/(?P<user_id>[^/]+)/unfollow$', user_views.UnFollowView.as_view(), name="user-unfollow-api"),
    url(r'^post/(?P<post_id>[^/]+)/like$', post_views.PostLikeView.as_view({'post': 'create','get':'list','delete':'unlike'}), name="post-like-api"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("users.urls")),
    path('posts/', include("posts.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.http.response import HttpResponseRedirect
from django.urls import path

from . import views
from posts.views import PostListView
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path('signup', views.SignUpFormView.as_view(), name="signup"),
    path('login/', views.LoginFormView.as_view(), name="login"),
    path('', PostListView.as_view(), name="home"),
    path('logout', views.logout_view, name="logout"),
    path('profile', views.SelfUserProfileView.as_view(), name="profile"),
    path('user/<pk>/profile', views.UserProfileView.as_view(), name="user-profile"),
    path('profile/update', views.ProfileUpdateView.as_view(), name="profile-update"),
    path('search/', views.SearchView.as_view(), name="search-users"),
    path('user/<pk>/follow', views.UserFollowView.as_view(), name="follow-user"),
    path('user/<pk>/unfollow', views.UserUnfollowView.as_view(), name="unfollow-user"),
]

users/forms.py
from users.models import UserProfile
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.forms import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.password_validation import MinimumLengthValidator, validate_password
from users.validators import NumberValidator, UppercaseValidator, LowercaseValidator, SymbolValidator
import re

UserModel = get_user_model()

class CustomUserCreationForm(forms.ModelForm):

    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password',)

class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password',)


class SignUpForm(forms.Form):
    username = forms.CharField(label="username", max_length=15)
    email = forms.EmailField(label="email_address")
    first_name = forms.CharField(label="First name", max_length=25, required=False)
    last_name = forms.CharField(label="Last name", max_length=25, required=False)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password", max_length=100,)
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label="Confirm Password", max_length=100)

    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")


        if re.match('^[0-9]', username) or re.match('^\.', username):
            raise ValidationError("Username cannot start with a number or a period(.)")

        if re.findall('\s', username):
            raise ValidationError("spaces are not allowed in username.")

        if UserModel.objects.filter(username=username).exists():
            raise ValidationError("Username already registered.")

        if UserModel.objects.filter(email=email).exists():
            raise ValidationError("Email address already resgistered.")

        password = validate_password(password=self.cleaned_data.get("password"))
        if self.cleaned_data.get("password") != confirm_password:
            raise ValidationError("Confirm password must match the password.")


    def save(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        password = self.cleaned_data.get("password")

        user = UserModel.objects.create_user(username=username, email=email, first_name=first_name, last_name=last_name, password=password)

        return user

class LoginForm(forms.Form):
    username = forms.CharField(label="Username or email")
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data.get("username")
        queryset = UserModel.objects.filter(Q(username=username) | Q(email=username))
        if not queryset.exists():
            raise ValidationError("User with given username or email does not exist!")
        return username

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'profile_pic', 'age', 'bio',]


    # def update_user(self, request):
    #     first_name = self.cleaned_data.get("first_name")
    #     last_name = self.cleaned_data.get("last_name")
    #     user = UserModel.objects.get(id=request.user.id)
    #     if user.first_name != first_name:
    #         user.first_name = first_name
    #         user.save()
    #     if user.last_name != last_name:
    #         user.last_name = last_name
    #         user.save()

api/users/views.py
from api.posts.serializers import PostSerializer
from datetime import datetime
from posts.models import Post
from django.shortcuts import render
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView, UpdateAPIView, GenericAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from .serializers import UserProfileSerializer, UserSerializer, UserLoginSerializer, UserSignUpSerializer
from users.models import User, UserProfile, UserFollower
from django.contrib.auth import login
from rest_framework.mixins import ListModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework.serializers import ValidationError
from rest_framework_jwt.settings import api_settings
from rest_framework import filters
from django.db.models import Q


class UserRegistrationView(CreateAPIView):

    serializer_class = UserSignUpSerializer
    permission_classes = (AllowAny,)

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        status_code = status.HTTP_201_CREATED
        response = {
            'success' : 'True',
            'status code' : status_code,
            'message': 'User registered successfully',
            }
        
        return Response(response, status=status_code)


class UserLoginView(APIView):

    permission_classes = (AllowAny,)
    serializer_class = UserLoginSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        response = {
            'success' : 'True',
            'status code' : status.HTTP_200_OK,
            'message': 'User logged in successfully',
            'token' : serializer.data['token'],
            }
        if api_settings.JWT_AUTH_COOKIE:
            expiration = (datetime.utcnow() + api_settings.JWT_EXPIRATION_DELTA)
            response_data = Response(response,status=status.HTTP_200_OK)
            response_data.set_cookie(api_settings.JWT_AUTH_COOKIE,response['token'],expires=expiration,httponly=True)
            return response_data

        status_code = status.HTTP_200_OK

        return Response(response, status=status_code)

class UserListView(ListAPIView):
    queryset = User.objects.all().order_by("username")
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)
    search_fields = ['username', 'first_name', 'last_name',]
    filter_backends = (filters.SearchFilter,)


class UserProfileView(RetrieveAPIView):

    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = UserSerializer

    def get(self, request):
        try:
            user = User.objects.get(email=request.user)
            serializer = self.serializer_class(user)
            status_code = status.HTTP_200_OK
            response = {
                'success': 'true',
                'status code': status_code,
                'data': serializer.data,
                }

        except Exception as e:
            status_code = status.HTTP_400_BAD_REQUEST
            response = {
                'success': 'false',
                'status code': status.HTTP_400_BAD_REQUEST,
                'message': 'User does not exists',
                'error': str(e)
                }
        return Response(response, status=status_code)


class UserProfileUpdateView(UpdateAPIView):

    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = UserProfileSerializer

    def put(self, request):
        try:
            user = UserProfile.objects.get(user=request.user.id)
            serializer = self.serializer_class(user, data=request.data)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            status_code = status.HTTP_200_OK
            serializer.data["status_code"] = status_code
            serializer.data["message"] = "User Profile Updated Successfully"
            return Response(serializer.data, status=status_code)

        except Exception as e:
            status_code = status.HTTP_400_BAD_REQUEST
            response = {
                'success': 'false',
                'status code': status.HTTP_400_BAD_REQUEST,
                'message': 'User does not exists',
                'error': str(e)
            }
            return Response(response, status=status_code)

class FollowView(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = UserProfileSerializer

    def get_queryset(self, user_id):
        try:
            user = User.objects.get(id=user_id)
            return user
        except:
            raise ValidationError("User not found.")

    def get(self, request, user_id):

        user = self.get_queryset(user_id)
        request_user = self.get_queryset(request.user.id)
        if not UserFollower.objects.filter(user=user_id, follower=request.user.id).exists():

            UserFollower.objects.create(user=user, follower=request_user)
            user = UserProfile.objects.get(user=user_id)
            request_user = UserProfile.objects.get(user=request.user.id)
            user.followers_count += 1
            request_user.following_count += 1
            user.save()
            request_user.save()
            serializer = self.serializer_class(user)
            status_code = status.HTTP_200_OK
            response = {
                'success': 'true',
                'status code': status_code,
                'message': 'User has been followed successfully',
                }

        else:
            status_code = status.HTTP_400_BAD_REQUEST
            response = {
                'success': 'false',
                'status code': status.HTTP_400_BAD_REQUEST,
                'message': 'You are already following this user.',
            }

        return Response(response, status=status_code)

class UnFollowView(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = UserProfileSerializer

    def get_queryset(self, user_id, request_id):
        try:
            follower_data = UserFollower.objects.get(user_id=user_id, follower_id=request_id)
            return follower_data
        except:
            raise ValidationError("You need to be a follower of the user to Unfollow.")

    def get(self, request, user_id):

        follower_data = self.get_queryset(user_id, request.user.id)
        follower_data.delete()

        user = UserProfile.objects.get(user=user_id)
        request_user = UserProfile.objects.get(user=request.user.id)
        user.followers_count -= 1
        request_user.following_count -= 1
        user.save()
        request_user.save()
        serializer = self.serializer_class(user)
        status_code = status.HTTP_200_OK
        response = {
            'success': 'true',
            'status code': status_code,
            'message': 'User has been unfollowed successfully',
            }
        
        return Response(response, status=status_code)


class SearchView(GenericAPIView):
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication

    def get_queryset(self, request):
        query = request.query_params.get('query')
        queryset = {}
        if query is not None:
            user_lookup = Q(username__icontains=query) | Q(first_name__icontains=query) | Q(last_name__icontains=query)
            post_lookup = Q(title__icontains=query) | Q(content__icontains=query)
            users = User.objects.filter(user_lookup)
            posts = Post.objects.filter(post_lookup)
            if users.exists():
                queryset['users'] = users
            else:
                queryset['users'] = []
            if posts.exists():
                queryset['posts'] = posts
            else:
                queryset['posts'] = []

        else:
            raise ValidationError("'query' parameter is required!")

        return queryset

    def get(self,request, *args, **kwargs):
        users = self.get_queryset(request)['users']
        posts = self.get_queryset(request)['posts']

        context = {'request': request}
        try:
            user_serializer = UserSerializer(users, many=True, context=context)
            post_serializer = PostSerializer(posts, many=True, context=context)

            status_code = status.HTTP_200_OK
            response = {
                'success': 'true',
                'status code': status_code,
                'users': user_serializer.data,
                'posts': post_serializer.data
            }
        except Exception as e:
            status_code = status.HTTP_400_BAD_REQUEST
            response = {
                'success': 'false',
                'status code': status.HTTP_400_BAD_REQUEST,
                'error': str(e)
            }

        return Response(response, status=status_code)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="{% static 'src/styles.css' %}" rel="stylesheet">

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

users/templates/users/login.html
{% extends "posts/home.html" %}
{% load static %}
{% block title %}
Login
{% endblock %}

{% block content %}
    <h1>Login to MySite</h1>
    <form class="forms" action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {% if invalid_user is True %}
        <p style="color: red;">Username and password did not match</p>
        {% endif %}
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
        <div class="content-section">
            <p>New to MySite? <a href="{% url 'users:signup' %}">Sign up</a> to join MySite</p>
        </div>
    </form>

{% endblock %}

users/templates/users/profile-update.html
{% extends "posts/home.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{user.username}} - Profile
{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "posts/home.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}
    <div class="content-section">
      <div class="media">
        {% if user.profile.profile_pic %}
        <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
        {% endif %}
        <div class="media-body">
          {% if user.profile.first_name is not None and user.profile.last_name is not None %}
          <h2>{{user.profile.first_name}} {{user.profile.last_name}}</h2>
          {% elif user.profile.first_name|length >= 1 %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{user.profile.first_name}}</h2></a>
          {% elif user.profile.last_name|length >= 1 %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{user.profile.last_name}}</h2></a>
          {% else %}
          <h2 class="account-heading">{{ user.username }}</h2>
          {% endif %}
          <h4 class="text-secondary">{{ user.username }}</h4>
          <p class="text-secondary">{{ user.email }}</p>
          {% if user.profile.bio is not None %}
          <p>{{user.profile.bio}}</p>
          {% endif %}
          {% if user.profile.age is not None %}
          <p>Age: {{user.profile.age}}</p>
          {% endif %}
          <p>{{user.profile.followers_count}} Followers</p>
          <p>{{user.profile.following_count}} Following</p>
        </div>
      </div>
      {% if request.user == user %}
      <div class="form-group">
        <a href="{% url 'users:profile-update' %}"><button class="btn btn-outline-info" type="submit">Edit Profile</button></a>
      </div>
      {% elif is_followed %}
      <h2 class="btn btn-outline-info">Following</h2>
      <div class="form-group">
        <a href="{% url 'users:unfollow-user' user.id %}"><button class="btn btn-outline-danger" type="submit">UnFollow</button></a>
      </div>
      {% elif not is_followed %}
      <div class="form-group">
        <a href="{% url 'users:follow-user' user.id %}"><button class="btn btn-outline-info" type="submit">Follow</button></a>
      </div>
      {% endif %}
    </div>
{% endblock content %}

users/templates/users/search_results.html
{% extends "posts/home.html" %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
  {% if request.GET.q != '' and users.exists %}
  {% for user in users %}
  <article class="media content-section">
    <div class="media">
        {% if user.profile.profile_pic %}
        <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
        {% endif %}
        <div class="media-body">
            {% if user.profile.first_name|length >= 1 and user.profile.last_name|length >= 1 %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{user.profile.first_name}} {{user.profile.last_name}}</h2></a>
            {% elif user.profile.first_name|length >= 1 %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{user.profile.first_name}}</h2></a>
            {% elif user.profile.last_name|length >= 1 %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{user.profile.last_name}}</h2></a>
            {% else %}
            <a href="{% url 'users:user-profile' user.id %}"><h2 class="account-heading">{{ user.username }}</h2></a>
            {% endif %}
            <h4 class="text-secondary">{{ user.username }}</h4>
            <p class="text-secondary">{{ user.email }}</p>
            {% if user.profile.bio is not None %}
            <p>{{user.profile.bio}}</p>
            {% endif %}
            {% if user.profile.age is not None %}
            <p>Age: {{user.profile.age}}</p>
            {% endif %}
            <p>{{user.profile.followers_count}} Followers</p>
            <p>{{user.profile.following_count}} Following</p>
        </div>
    </div>
  </article>
  {% endfor %}
  {% else %}
  <h2>No search results for this query</h2>
  {% endif %}
{% endif %}
{% endblock %}

users/templates/users/signup.html
{% extends "posts/home.html" %}
{% load static %}
{% block title %}
Sign Up
{% endblock %}

{% block content %}
    <h1>Sign up to MySite</h1>
    <div class="content-section">
        <form class="forms" action="{% url 'users:signup' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
    </div>
    <div class="content-section">
        <p>Already have an account in MySite? <a href="{% url 'users:login' %}">Login</a></p>
    </div>

{% endblock %}