api/urls.py
from django.conf.urls import url
from .users import views as user_views
from .posts import views as post_views

urlpatterns = [
    url(r'^signup', user_views.UserRegistrationView.as_view(), name="signup-api"),
    url(r'^login', user_views.UserLoginView.as_view(), name="login-api"),
    url(r'^users', user_views.UserListView.as_view(), name="users-list-api"),
    url(r'^search', user_views.SearchView.as_view(), name="search-api"),
    url(r'^user/profile', user_views.UserProfileView.as_view(), name="user-profile-api"),
    url(r'^profile/update', user_views.UserProfileUpdateView.as_view(), name="profile-update-api"),
    url(r'^post/create', post_views.PostCreateView.as_view(), name="post-create-api"),
    url(r'^posts/list', post_views.PostsListView.as_view(), name="posts-list-api"),
    url(r'^post/(?P<pk>[^/]+)/update$', post_views.PostUpdateView.as_view(), name="post-update-api"),
    url(r'^post/(?P<post_id>[^/]+)/delete$', post_views.PostDeleteView.as_view(), name="post-delete-api"),
    url(r'^posts$', post_views.PostFeedView.as_view(), name="post-feed-api"),
    url(r'^user/(?P<user_id>[^/]+)/follow$', user_views.FollowView.as_view(), name="user-follow-api"),
    url(r'^user/(?P<user_id>[^/]+)/unfollow$', user_views.UnFollowView.as_view(), name="user-unfollow-api"),
    url(r'^post/(?P<post_id>[^/]+)/like$', post_views.PostLikeView.as_view({'post': 'create','get':'list','delete':'unlike'}), name="post-like-api"),
]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = "posts"

urlpatterns = [
    # path('', views.PostListView.as_view(), name="posts-list"),
    path('create', views.PostCreateView.as_view(), name="post-create"),
    path('', views.PostListView.as_view(), name="posts-feed"),
    path('<pk>', views.PostDetailView.as_view(), name="post-detail"),
    path('<pk>/update', views.PostUpdateView.as_view(), name="post-update"),
    path('<pk>/delete', views.PostDeleteView.as_view(), name="post-delete"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("users.urls")),
    path('posts/', include("posts.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.http.response import HttpResponseRedirect
from django.urls import path

from . import views
from posts.views import PostListView
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path('signup', views.SignUpFormView.as_view(), name="signup"),
    path('login/', views.LoginFormView.as_view(), name="login"),
    path('', PostListView.as_view(), name="home"),
    path('logout', views.logout_view, name="logout"),
    path('profile', views.SelfUserProfileView.as_view(), name="profile"),
    path('user/<pk>/profile', views.UserProfileView.as_view(), name="user-profile"),
    path('profile/update', views.ProfileUpdateView.as_view(), name="profile-update"),
    path('search/', views.SearchView.as_view(), name="search-users"),
    path('user/<pk>/follow', views.UserFollowView.as_view(), name="follow-user"),
    path('user/<pk>/unfollow', views.UserUnfollowView.as_view(), name="unfollow-user"),
]

posts/models.py
from django.db import models
import uuid
from PIL import Image
from datetime import datetime
from users.models import User
from django.utils import timezone
from src.utils import hex_uuid

# Create your models here.

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=hex_uuid, editable=False)
    title = models.CharField(max_length=150)
    content = models.TextField()
    photo = models.ImageField(upload_to='post-photos/', null=True, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    likes_count = models.PositiveBigIntegerField(verbose_name="Likes Count", default=0)
    comments_count = models.PositiveBigIntegerField(verbose_name="Comments Count", default=0)

    class Meta:
        db_table = "posts"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.photo and self.photo is not None:
            img = Image.open(self.photo.path)
            if img.height > 500 or img.width > 500:
                output_size = (500, 500)
                img = img.resize(output_size)
            img.save(self.photo.path)


class PostLikes(models.Model):
    id = models.UUIDField(primary_key=True, default=hex_uuid, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="liked_post")

    class Meta:
        db_table = "post_likes"

posts/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content', 'photo', 'date_posted', 'user')

api/posts/views.py
from django.shortcuts import render
from rest_framework import status
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView, RetrieveUpdateAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.serializers import ValidationError
from .serializers import PostSerializer
from api.users.serializers import UserProfileSerializer 
from users.models import User, UserFollower, UserProfile
from posts.models import Post, PostLikes
from rest_framework.mixins import ListModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework import filters
from rest_framework.viewsets import ViewSet, ModelViewSet
from rest_framework.decorators import action

# Create your views here.
class PostCreateView(CreateAPIView):

    serializer_class = PostSerializer
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication

    def post(self, request):
        user = User.objects.get(id=request.user.id)
        post = Post(user=user)
        serializer = self.serializer_class(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        status_code = status.HTTP_201_CREATED
        response = {
            'success' : 'True',
            'status code' : status_code,
            'message': 'Post created successfully',
            'post_detail': serializer.data,
            }
        
        return Response(response, status=status_code)

class PostsListView(ListAPIView, ListModelMixin):

    queryset = Post.objects.all().order_by('-date_posted')
    serializer_class = PostSerializer
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    search_fields = ['title', 'content',]
    filter_backends = (filters.SearchFilter,)


class PostUpdateView(RetrieveUpdateAPIView):

    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = PostSerializer
    queryset = Post.objects.all()

    def put(self, request, pk):
        try:
            post = Post.objects.get(id=pk)
            if post.user_id != request.user.id:
                raise ValidationError("User cannot edit/update other users posts.")
            else:
                serializer = self.serializer_class(post, data=request.data)
                serializer.is_valid(raise_exception=True)
                serializer.save()
                status_code = status.HTTP_200_OK
                serializer.data["status_code"] = status_code
                serializer.data["message"] = "Post Updated Successfully"
                return Response(serializer.data, status=status_code)

        except Exception as e:
            status_code = status.HTTP_404_NOT_FOUND
            response = {
                'success': 'false',
                'status code': status.HTTP_404_NOT_FOUND,
                'message': 'Post Not Found!',
                'error': str(e)
            }
            return Response(response, status=status_code)

class PostDeleteView(DestroyAPIView):

    serializer_class = PostSerializer
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication

    def get_queryset(self, post_id):
        try:
            post = Post.objects.get(id=post_id)
            return post
        except:
            raise ValidationError("Post not found.")

    def delete(self, request, post_id):

        post = self.get_queryset(post_id)
        if post and post.user_id == request.user.id:
            post.delete()
        else:
            raise ValidationError("User cannot delete other users posts.")
        
        status_code = status.HTTP_200_OK
        response = {
            'success' : 'True',
            'status code' : status_code,
            'message': 'Post deleted successfully',
        }
        return Response(response, status=status_code)

class PostFeedView(ListAPIView):

    serializer_class = PostSerializer
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication

    def get_queryset(self, request_user_id):
        users_followings = UserFollower.objects.filter(follower=request_user_id)

        if users_followings.exists():
            users_list = list(users_followings.values_list('user', flat=True))
        else:
            users_list = []
        
        users_list.append(request_user_id)
        posts = Post.objects.filter(user_id__in=users_list).order_by('-date_posted')

        return posts

    def list(self, request):
        queryset = self.get_queryset(request.user.id)
        serializer = PostSerializer(queryset, many=True)
        status_code = status.HTTP_200_OK
        response = {
            'success' : 'True',
            'status code' : status_code,
            'posts': serializer.data,
        }
        return Response(response, status=status_code)

class PostLikeView(ModelViewSet):
    """
    create: create a user's like for a post
    list: List likes of a post
    unlike: delete like on a post
    """
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    serializer_class = PostSerializer

    def get_queryset(self, post_id):
        try:
            queryset = Post.objects.get(id=post_id)
        except:
            raise ValidationError('Post not found.')

        return queryset

    def list(self,request,post_id):
        post = self.get_queryset(post_id)
        likes = list(PostLikes.objects.filter(post=post).values_list('user',flat=True))
        users_profile = UserProfile.objects.filter(user_id__in=likes).order_by('first_name')
        self.serializer_class = UserProfileSerializer
        serializer = self.serializer_class(users_profile,many=True)
        status_code = status.HTTP_200_OK
        response = {
            'success': 'true',
            'status code': status_code,
            'likes': serializer.data,
        }
        return Response(response, status=status_code)

    def create(self,request,post_id):
        post = self.get_queryset(post_id)
        if not PostLikes.objects.filter(post=post_id, user=request.user.id).exists():
            PostLikes.objects.create(post=post,user=request.user)
            post.likes_count += 1
            post.save()
            serializer = self.serializer_class(post)
            status_code = status.HTTP_200_OK
            response = {
                'success': 'true',
                'status code': status_code,
                'message': 'Post has been liked successfully',
                'post': serializer.data,
                }
        else:
            status_code = status.HTTP_400_BAD_REQUEST
            response = {
                'success': 'false',
                'status code': status.HTTP_400_BAD_REQUEST,
                'message': 'This Post is already liked',
            }

        return Response(data=response,status=status_code)

    @action(detail=True, methods=['delete'])
    def unlike(self,request,post_id):
        post = self.get_queryset(post_id)
        try:
            like = PostLikes.objects.get(post_id=post.id, user_id=request.user.id)
            if like and like.user_id == request.user.id:
                like.delete()
            else:
                raise ValidationError("User cannot delete likes of other users")

            post.likes_count -= 1
            post.save()
            serializer = self.serializer_class(post)
            status_code = status.HTTP_200_OK
            response = {
            'success' : 'True',
            'status code' : status_code,
            'message': 'Post has been unliked successfully',
            'post': serializer.data
            }
        except:
            status_code = status.HTTP_404_NOT_FOUND
            response = {
            'success' : 'True',
            'status code' : status_code,
            'message': 'Post like not found',
            }

        return Response(response, status=status_code)

posts/views.py
from posts.forms import PostCreateForm
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.auth import get_user_model
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.
class PostCreateView(LoginRequiredMixin, CreateView):

    model = Post
    fields = ('title', 'content', 'photo',)
    success_url = reverse_lazy('posts:posts-feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_feed.html'
    # context_object_name = 'posts'
    # ordering = ['-date_posted']
    
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        else:
            return render(request, self.template_name, {'posts': Post.objects.all().order_by('-date_posted')})

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = Post
    fields = ('title', 'content', 'photo',)
    success_url = reverse_lazy('posts:posts-feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = Post
    template_name = 'posts/post_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:posts-feed')


    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False

posts/templates/posts/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'posts/main.css' %}">

    {% if title %}
        <title>MySite - {{ title }}</title>
    {% else %}
        <title>MySite</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'posts:posts-feed' %}">MySite</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'posts:posts-feed' %}">Home</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <form class="nav-item nav-link" method="GET" value="{{request.GET.q}}" action="{% url 'users:search-users' %}" style="margin: 0">
                <input id="search_box" type="text" name="q" value="{{request.GET.q}}" placeholder="Search">
                <button id="search_submit" type="submit" >Submit</button>
              </form>
              <a class="nav-item nav-link" href="{% url 'posts:post-create' %}">New Post</a>
              <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'users:signup' %}">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{message}}</div>
          {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/post_delete.html
{% extends "posts/home.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete this post? </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'posts:post-detail' post.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends "posts/home.html" %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
        <article class="media content-section">
          {% if post.user.profile.profile_pic %}
          <img class="rounded-circle article-img" src="{{post.user.profile.profile_pic.url}}">
          {% endif %}
          <div class="media-body">
            <div class="article-metadata">
              {% if post.user.first_name|length > 1 and post.user.last_name|length >= 1 %}
                <a class="mr-2" href="{% url 'users:user-profile' post.user.id %}">{{ post.user.first_name }}  {{ post.user.last_name }}</a>
              {% else %}
                <a class="mr-2" href="{% url 'users:user-profile' post.user.id %}">{{ post.user.username }}</a>
              {% endif %}
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.photo %}
            <img class="article-image" src="{{post.photo.url}}">
            {% endif %}
          </div>
          {% if user == post.user %}
          <div class="article-metadata">
          <div class="form-group">
            <a href="{% url 'posts:post-update' post.id %}"><button class="btn btn-outline-info" type="submit">Edit Post</button></a>
          </div>
          <div class="form-group">
            <a href="{% url 'posts:post-delete' post.id %}"><button class="btn btn-outline-danger" type="submit">Delete Post</button></a>
          </div>
          </div>
          {% endif %}
        </article>
  {% endif %}
{% endblock content %}

posts/templates/posts/post_feed.html
{% extends "posts/home.html" %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    {% for post in posts %}
        <article class="media content-section">
          {% if post.user.profile.profile_pic %}
          <img class="rounded-circle article-img" src="{{post.user.profile.profile_pic.url}}">
          {% endif %}
          <div class="media-body">
            <div class="article-metadata">
              {% if post.user.first_name|length > 1 and post.user.last_name|length >= 1 %}
                <a class="mr-2" href="{% url 'users:user-profile' post.user.id %}">{{ post.user.first_name }}  {{ post.user.last_name }}</a>
              {% else %}
                <a class="mr-2" href="{% url 'users:user-profile' post.user.id %}">{{ post.user.username }}</a>
              {% endif %}
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'posts:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.photo %}
            <img class="article-image" src="{{post.photo.url}}">
            {% endif %}
          </div>
        </article>
      {% endfor %}
  {% endif %}
{% endblock content %}

posts/templates/posts/post_form.html
{% extends "posts/home.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}